### PR TITLE
feat: New parameters for Client websocket packet data size

### PR DESCRIPTION
**Pull request by mokocup**
# Description

When you playing with big modpack , the Netty will throw `Max frame length of 65536 has been exceeded.`. So you need a way to change websocket max packet size via config, since you don't use Forge Config so I add the input via Parameter

### CODE REVIEW

**Comment by rikka0w0** [comment]
Thanks for your hard work!
I saw you also posted an [issue](https://github.com/rikka0w0/wsmc/pull/1), does this pr relate to that one?

**Comment by mokocup** [comment]
> Thanks for your hard work! I saw you also posted an [issue](https://github.com/rikka0w0/wsmc/pull/1), does this pr relate to that one?

Yes that correct , #3 having two problem which resolved in this pull

1. Netty Frame itself only support max 65536 length , If you play on big modpack(300+ mods) like ATM9 , Vault Hunter. Netty will throw error and dont allow you connect at all ([f71c9b1](https://github.com/rikka0w0/wsmc/pull/1/commits/f71c9b1d325edf4b88893cce457fca22cfb6e812))
2. Cloudflare SSL have SNI and Netty verify it which make it disconnect again  ([024580e](https://github.com/rikka0w0/wsmc/pull/1/commits/024580e1f78dc8c92669cd8db38943af68ec2711))

**Comment by rikka0w0** [comment]
> 1. Netty Frame itself only support max 65536 length 

I think there is a better fix for this. The Minecraft protocol is built on top of TCP (only exposes streams, not frames), and it is supposed to support frame reconstruction. When our WebSocket frame composer receives a sending request from the higher-level Minecraft protocol layer, if the amount of data requested to send is greater than 65535 bytes, we split it into multiple smaller WebSocket frames, each with a size less than or equal to 65536 bytes. On the recipient end, it should make no difference, then we can get rid of `wsmc.maxFramePayloadLength`.

Another reason I am against `wsmc.maxFramePayloadLength` is that the Minecraft protocol assumes the underlying transmission layer to be a stream. We should use WebSocket to mimic a stream where possible. Using a large buffer may increase the latency, as each WebSocket frame must be fully received before it can be passed to the Minecraft protocol layer.

> 2. Cloudflare SSL have SNI and Netty verify it which make it disconnect again

Thanks for pointing this out and fixing it. Cloudflare won't accept an HTTPS connection with an incorrect SNI or without an SNI. I thought Netty would append an SNI automatically.

I'm also thinking of adding a client-side option to let the client specify SNI and server hostname/IP address. This can be useful when the SNI resolves to a slow or unreachable route. In mainland China, Cloudflare hostnames may resolve to IP addresses that are further away, which cannot guarantee minimum latency.

My proposed format (to be typed in the address box) is:
`{"sni": "server.behind.cloudflare.com"}:wss://ifconfig.co/minecraft_server_url`
The above example represents a secured WebSocket to the Cloudflare network, with `server.behind.cloudflare.com` as the SNI to indicate the destination (The Minecraft server) and `ifconfig.co` as the hostname/IP address to indicate the entry of the Cloudflare network.

The JSON before the `wss` scheme specifies WSMC-specific options during this connection. A client can use it to gain more control over the connection. Furthermore, we may have this to skip the SSL certificate verification:
`{"insecure": true}`

**Comment by stevefan1999-personal** [comment]
> I think there is a better fix for this.

Blocked by https://github.com/netty/netty/issues/9730

> When our WebSocket frame composer receives a sending request from the higher-level Minecraft protocol layer, if the amount of data requested to send is greater than 65535 bytes, we split it into multiple smaller WebSocket frames

That's not true, it is a default limit of 64K set by Netty's WebSocket handler for some reason. You can set the max frame size to 2^64 -1 if you want.

> Using a large buffer may increase the latency, as each WebSocket frame must be fully received before it can be passed to the Minecraft protocol layer

That's not true either. It is a **max** frame payload size, that **not each frame has to be this big**. So, there is no problem in setting a bigger buffer size. The actual buffer size is adaptive, depending on the WebSocket frame size parameter, which is defined in the protocol spec, meaning it will be dynamically resized and adjusted. The maximum payload size thus is simply a hint/suggestion to the handler. You can still send a 32K frame in a 1MB max frame buffer size, and only use exactly 32K memory for buffering.

In fact, [IP packet itself would also fragment into smaller sizes if too big](https://en.wikipedia.org/wiki/IP_fragmentation), and this is done by the OS level. We are just doing this again in application level, handled by Netty.

**Comment by mokocup** [comment]
> I think there is a better fix for this.

Split data  is actually make stuff more complex than you think, i think about some cons of it like
- Add complexity between client and server since you add another layer for split and merge data.
- Increase CPU usage and Ram usage for both client and server since it need store temp data
> When our WebSocket frame composer receives a sending request from the higher-level Minecraft protocol layer, if the amount of data requested to send is greater than 65535 bytes, we split it into multiple smaller WebSocket frames

Like @stevefan1999-personal said , this is Netty limit themself in lib , not websocket limit that why they offer you parameter to change it. Vanilla Minecraft also have limit data size by default , you can check some Mod that attempt to fix it by increase the cap
https://github.com/lazul1ne/XXLPackets/blob/6591207f3d5a7306a2347ad2255eb231ce1bcf6e/src/main/java/tfar/xlpackets/mixin/PackeEncoderMixin.java#L12
https://github.com/TonimatasDEV/PacketFixer

> Using a large buffer may increase the latency, as each WebSocket frame must be fully received before it can be passed to the Minecraft protocol layer.

Smaller buffer will increase latency more than large buffer even you send multiple small buffer simultaneously, you still need them in sequence so large buffer are better than small.

> My proposed format (to be typed in the address box) is: {"sni": "server.behind.cloudflare.com"}:wss://ifconfig.co/minecraft_server_url

I don't think this is a good format, it don't have any delimiter, url go way to behind and server don't know what user config unless you send payload.
Websocket URL support parameter, it also send to server, it standard and shorter than json (json add 5 character per property)

**Comment by rikka0w0** [comment]
Thanks for pointing out that the 64kB limit was imposed by Netty, not the WebSocket standard. So, let's merge the `wsmc.maxFramePayloadLength` now.

> Websocket URL support parameter, it also send to server, it standard and shorter than json (json add 5 character per property)

The JSON in front of the schema only defines information that only the client needs to start a connection. For example, let the client disable SSL certificate verification or use a custom SNI to start an HTTPS session. The SNI will be sent to the server in the SSL handshake anyway, and the server don't really need to know if the client chose to disable SSL certificate verification. That's why I prefer to keep these options out of the URL parameter.

The URL parameters, on the other hand, if any, will be sent to the server as intended and untouched.

Putting the SNI and insecure options in the URL parameter is definitely feasible. But doing so may require us to strip them before we send the request. Their existence may change the behavior of something in the middle. Remember that the WebSocket may need to go through several relays before it can reach the actual game server.

But again, feel free to post your thoughts here.

**Pull request merged**
